name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  PROJECT_DIR: cifras_significativas

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./${{ env.PROJECT_DIR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: ./${{ env.PROJECT_DIR }}/package-lock.json

      - name: Install dependencies
        run: npm ci

      # Debe usar output:'export' desde cifras_significativas/next.config.cjs
      - name: Build
        run: npm run build

      # Debug: imprimimos qué generó el build
      - name: Show build output (debug)
        run: |
          echo "PWD:" && pwd
          echo "== listing =="
          ls -la
          echo "== show next.config.cjs =="
          sed -n '1,200p' next.config.cjs || true
          echo "== .next =="
          ls -la .next || true
          echo "== out =="
          ls -la out || true

      # Fallar de forma clara si no existe out/
      - name: Ensure out/ exists
        run: |
          if [ ! -d "out" ]; then
            echo "❌ No se generó ./out. Asegurate de tener output: 'export' en next.config.cjs y que TODAS las rutas sean estáticas (○/●)."
            exit 1
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./${{ env.PROJECT_DIR }}/out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
